---
- name: Creating User
  hosts: nodes
  
  tasks: 
  - name: Creating User
    user: 
      name: kubeclient
      state: present

- name: Installing Packages
  hosts: all

  tasks: 
  - name: Install GIT
    package: 
      name: git
      state: present

  - name: Installing Multiple Packages
    package: 
      state: present
      name: 
        - java
        - maven

- name: Installing Package and Starting a Service
  hosts: master

  tasks: 
  - name: Install NTP Package
    package:
      name: ntp
      state: present

  - name: Starting NTPD Service
    service: 
      name: ntpd
      state: started
      enabled: yes
